language: python
python:
  - "3.8"

stages:
  - lint
  - test

jobs:
  include:
    - stage: "Lint"
      name: "Black"
      install:
        - pip install -r requirements.txt
      script:
        - black . --check --diff
    - stage: "Test"
      name: "Pytest"
      install:
        - pip install -r requirements.txt
      script:
        - pytest test
